version: '3.8'

services:
  ollama-power-interface:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_API_URL=${OLLAMA_API_URL:-http://ollama:11434}
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - default
      - core_proxy-manager
      - ollama
    restart: unless-stopped

networks:
  core_proxy-manager:
    external: true
  ollama:
    external: true
