services:
  ollama-power-interface:
    build: .
    environment:
      - OLLAMA_API_URL=${OLLAMA_API_URL:-http://ollama:11434}
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - core_proxy-network
      - ollama
    restart: unless-stopped

networks:
  core_proxy-network:
    external: true
  ollama:
    external: true
